[pytest]
testpaths = test_cases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -s --html=test_reports/report.html --self-contained-html
markers =
    smoke: 冒烟测试
    regression: 回归测试
    p0: 优先级P0用例